### ISSUE TITLE
Event Calendar - Error message when trying to access page - HTTP 500 error.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#76] opened 2017-06-20 12:42 UTC
I pressed back on the browser and got this message - 
![screen shot 2017-06-20 at 8 41 17 am](https://user-images.githubusercontent.com/8631079/27333602-6a88209c-5594-11e7-890d-66d7ae54eaeb.png)

**Comment by ccmorris** [comment] 2017-06-20 12:52
caused by an update to drupal core, overwriting a patch for the core datetime module. this is closed by f9305ac

**Closed as completed by ccmorris** 2017-06-20 12:52 UTC
Labels: bug
